### ISSUE TITLE
Submit to wbond repository

### ISSUE THREAD

**Issue by anilgulecha** [poritsky/fountain-sublime-text#2]
Can you submit this to the repository: http://wbond.net/sublime_packages/community
- you'll need to add a package-metadata.json file - look at the AAAPackageDev package for an example.

This will make it easy for people to simply download and install the package from the menu.

**Comment by ikester** [comment]
I created a pull request for this:
https://github.com/wbond/package_control_channel/pull/789

According to http://wbond.net/sublime_packages/package_control/package_developers, package-metadata.json SHOULD NOT be included in the repository.

**Comment by poritsky** [comment]
How can I help?

**Comment by ikester** [comment]
At this point, I don't think you need to do anything. If you take a look at the pull request I sent (see above) you'll see that I just added your repo and a mapping name to a packages file that they curate. I've never submitted a module to them before so I don't know how long it takes for them to accept it.

Unless you object to having your repo on the Sublime Package Control list for some reason, I don't think there is anything else to be done. Once it's accepted it just means that people with SPC will be able to install your Fountain module by picking it from a list of packages. If anything, it'll increase your work's visibility to the Sublime Text community.

**Comment by poritsky** [comment]
Awesome. Haven't messed with this project in a while. Thanks for doing the leg work to get this up.

**Comment by ikester** [comment]
You're welcome. We'll see if some more people get curious/interested about typing scripts in Sublime Text 2.
